### ISSUE TITLE
Missing GPG signature

### ISSUE THREAD

**Issue by FFY00** [eradman/entr#10]
Hey, could you sign the latest source with GPG too (`.asc` is missing)?

http://eradman.com/entrproject/code/

**Comment by eradman** [comment]
I was trying to figure out how to get gpg working yesterday, with no success... it hangs and does not prompt for a password

```
$ gpg2 --pinentry-mode loopback -a --detach-sign entr-4.3.tar.gz
^C
gpg: signal Interrupt caught ... exiting
```

```
$ cat ~/.gnupg/gpg-agent.conf
allow-loopback-pinentry
```

```
$ ps -x | grep gpg
 9827 ??  Ss      0:00.01 gpg-agent --homedir /home/eradman/.gnupg --use-standard-socket --daemon
 5037 pj  S+      0:00.03 gpg2 --pinentry-mode loopback -a --detach-sign entr-4.3.tar.gz
```

**Comment by FFY00** [comment]
Hum... that seems like an issue with your gpg agent setup. Have you tried without `--pinentry-mode loopback`?

This is how the gpg agent is started in my machine:
```
$ ps aux | grep gpg
168228 ?        SLs    0:08 /usr/bin/gpg-agent --supervised
```
But I am running gnome keyring daemon (even though I am on i3).

**Comment by eradman** [comment]
I have had this trouble before. Tried this as well

```
$ gpg2 -a --detach-sign entr-4.3.tar.gz
gpg: error retrieving key fingerprint from card: Input/output error
gpg: signing failed: No such file or directory
gpg: signing failed: No such file or directory
```

And now it worked!

```
$ gpg2 --pinentry-mode loopback -a --detach-sign entr-4.3.tar.gz
gpg: error retrieving key fingerprint from card: Input/output error
```

`entr-4.3.tar.gz.asc` is available now

**Comment by FFY00** [comment]
Great! But now I can't find your key :joy:.

Did you push it to any keyservers? I looked through your website but I didn't find any key there either.

**Comment by eradman** [comment]
I don't have a keyserver. You can fetch it at http://eradman.com/entrproject/code/entr-4.3.tar.gz.asc

**Comment by FFY00** [comment]
That's the signature. I need your public key to verify it.

If you push it to a place such as the [SKS Keyservers](http://pool.sks-keyservers.net/) I can just fetch it from the terminal with `gpg --recv-keys 5C418B8631BC7C26`.

**Comment by eradman** [comment]
I see what you're saying. And you're right; I don't have a link to it anywhere. The public key is at

http://eradman.com/files/gpg.asc

**Comment by FFY00** [comment]
Thanks, just pushed the new version to Archlinux.
