### ISSUE TITLE
Enhancement: Report changed path

### ISSUE THREAD

**Issue by RobertLarsen** [eradman/entr#101]
At times it could be beneficial to know the path of the file/directory that changed when my command is run by `entr`.

I've had an issue where my command made a change in a file monitored by `entr` with an endless rebuild cycle as a result. I had to `strace` in order to debug this.

A simple environment variable with the path would be nice.

**Comment by kopsha** [comment]
From my understanding`entr` does not change paths... unless I'm missing something.

**Comment by RobertLarsen** [comment]
No, but it monitors for changes...and the program that `entr` executes when it detects a change may change something which `entr` detects and executes the program, which may change something, which `entr` detects, which....and so on.

**Comment by kopsha** [comment]
I understand the endless loop that gets created, and I think that the problem you have is outside the scope of the tool.
I do not know your full context, but I would try a different setup that does not trigger this loop. Maybe you are doing too many things with a single command and it may be worth to break it down.

**Comment by RobertLarsen** [comment]
That is what I want, but I do not know which file is touched and so why this loop is triggered (well, I do, but only after a lot of debugging). I run a build and test chain and it does a gazillion things. If `entr` would somehow tell what triggered the command (through a log file or environment variable or whatever) debugging this would have been immensely easier.

**Comment by kopsha** [comment]
Ok, now I understand what enhancement you are requesting, it makes sense. Thanks.

**Comment by eradman** [comment]
@RobertLarsen you can set `EV_TRACE` to see the events as they are processed

```
ag -l | EV_TRACE=1 entr make
```

This was meant as a means of debugging issues with `entr` itself, but I think it will work for your case. The "leading edge" (first file to trigger an event) is accessible on the command line as well by printing the special filename `/_`

```
ag -l | entr echo /_
```

Another way to get at this data (not documented) is that `$0` is set to the leading edge when using the `-s` flag

```
ag -l entr -s 'echo $0'
```
