### ISSUE TITLE
entr is running twice

### ISSUE THREAD

**Issue by sbaildon** [eradman/entr#106]
possibly related; [entr on big sur is not in sync #78](https://github.com/eradman/entr/issues/78)

I'm running entr with

```bash
git ls-files | entr make -j4
```

and I see entr firing twice for what should be a single write event

```bash
# EV_TRACE=1
0/1: fflags: 0x20 r 100644 myfile.txt
# something happens...
0/1: fflags: 0x8 r 100644 myfile.txt
# 0x8 event fires immediately afterwards
```

my `entr`

```
~/s/s/events $ entr
release: 5.2
usage: entr [-acdnprsz] utility [argument [/_] ...] < filenames
```

**Comment by eradman** [comment]
I was able to reproduce this on MacOS (13.0.1)

It appears that after files are updated by `git` a series of attribute changes are emitted where the inode appears to have changed

```
0/2: fflags: 0x8 r 100644 Makefile.macos
inode changed: 15679245 -> 15679299
```

**Comment by eradman** [comment]
There is no mention of delayed `NOTE_ATTRIB` events in the [kqueue(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/kqueue.2.html) man page or in `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/event.h`

Responding these events was for a corner case on Linux. Commit 2d17193 should solve this by enabling this response only when `-a` is specified.

**Comment by sbaildon** [comment]
I've built `entr` from source and I've not seen the issue so far

**Comment by eradman** [comment]
Excellent! I'll aim to tag a release later this week that includes this change.

**Comment by eradman** [comment]
Turns out responding to these attribute updates is important on Linux. Modified the previous change to simply re-enable this behavior on Linux only in commit 828a2a42adfe05fc92af2ac383ebdaa39afe2291.
