### ISSUE TITLE
How to deal with user input?

### ISSUE THREAD

**Issue by tamis-laan** [eradman/entr#115]
I have a little go program:

``` go
package main

import (
	"fmt"
)

func main() {
	var inp string

	for {
		fmt.Println("yourinput", inp)
		fmt.Scan(&inp)
	}
}
```
It waits for user input with `fmt.Scan(&test)`. I'm using entr to look for changes and restart the app:
``` bash
fd -e go | entr -r go run main.go
```
This results in an infinite loop printing "your input:". I would like to provide the input my self.

**Comment by eradman** [comment]
The problem here is that the restart option (`-r`) starts the utility as a background process which does not have access to `STDIN`.

If you run it without this option your program will be run with control of the TTY.

**Comment by tamis-laan** [comment]
But without the restart option `-r` the program wont restart when I make a change to the code...

**Comment by arkamar** [comment]
Yes, this is also expected behaviour, but you can trick it with `fifo(7)`. In one console create a named pipe and open `cat` to it
```sh
mkfifo fifo
cat >fifo
```
Then start the `entr` in next console like this:
```sh
fd -e go | entr -r sh -c '<fifo exec go run main.go'
```
everything you write to `cat` will be piped to go. Moreover, you can redirect output from `echo`, `cat` or other commands in different console to `fifo` as well, because it behaves like funnel.

**Comment by xakon** [comment]
Amazing solution!  I have many cases in mind where I can apply this technique.

**Comment by arkamar** [comment]
Btw, there is one other trick in case you don't want consumer to exit when all write ends of funnel are closed. It is useful when you don't want `cat >fifo` running whole time but for example `echo test >fifo` is just enough. In that case you need to have both ends of the `fifo` open in consumer on file descriptor which is never read or written.
```sh
# consumer
10<>fifo <fifo cat
```
Then you can `echo test >fifo` from another console multiple times without any issue.

**Comment by eradman** [comment]
Indeed--I just illustrated why using `pkill` is probably not a good approach.
