### ISSUE TITLE
Alternatives to SIGTERM with -r

### ISSUE THREAD

**Issue by lodthe** [eradman/entr#121]
When `-r` option is used, entr acts as follows:
>  SIGTERM is used to terminate the utility before it is restarted.

Some tools are written to wait other signals to quit gracefully. For example, I use entr to reload a utility that waits specifically for SIGINT.

For such cases, it would be nice to use a different signal instead of SIGTERM. As I see it, it could be configured with another flag.

**Comment by eradman** [comment]
This would be easy enough to implement. What flag would you use to indicate the signal? ( [man page](http://eradman.com/entrproject/entr.1.html) )

**Comment by lodthe** [comment]
I think you have a better vision as a maintainer :) 

`-s` would be an ideal option, but it's already used. What about `-q` (quit), `-t` (terminate) or `-k` (kill)?
Also, we can think about something like `-S` and `-rs` (reload signal), but they differ from the current naming conventions.

**Comment by eradman** [comment]
I'm thinking we probably should support an arbitrary signal number, which rules out -q/-t/-k... As you say, `-s` would be ideal (this is what timeout(1) uses)

An environment variable `ENTR_RESTART_SIG` could be used, but this would be more appropriate as a workaround.

New argument `-R signal` would do it.

I tried unsuccessfully to find a "signal relay utility" that would trap SIGTERM and deliver an alternate signal, something like this

```
ls *.rb | entr -r sigexec -INT ruby main.rb
```

**Comment by eradman** [comment]
The way kill(1) parses arguments is not standard by any argument parsing standard, but I kind of like it. I'm considering supporting `-INT`, `-TERM`, `-QUIT`, `-USR1` as flags

```
ls *.rb | entr -r -INT ruby main
```

**Comment by lodthe** [comment]
Looks good!

Will these flags (`-INT`, `-TERM`, ...) be available only when the `-r` flag is specified?

**Comment by eradman** [comment]
Yes, because without `-r` entr never sends a signal, it simply waits for the utility to exit

**Comment by eradman** [comment]
I posted an experimental implementation in [restart-signal](https://github.com/eradman/entr/tree/restart-signal) branch.

**Comment by eradman** [comment]
I decided to try solving this by creating a separate utility [sigrelay](https://github.com/eradman/sigrelay) which listens for `SIGTERM` and sends an alternate signal.

```
ls *.rb | entr -r sigrelay -2 ruby main.rb
```

It's in early stages, but should work well enough to try. @turip please give it a try

**Comment by eradman** [comment]
I realized that the utility I wrote is very close to what the [timeout(1)](http://man.openbsd.org/timeout.1) utility does.

```
ls *.rb | entr -r timeout -s 2 0 ruby main.rb
```

Where
```
0 disable timeout
-s 2 sends SIGINT
```

Signals are propagated by default

**Comment by eradman** [comment]
Updated http://eradman.com/entrproject/ with this technique. Closing

**Comment by lodthe** [comment]
Thanks for the trick with `timeout`! 👍
