### ISSUE TITLE
Use strlcpy with >=glibc-2.38

### ISSUE THREAD

**Issue by thesamesam** [eradman/entr#122]
glibc-2.38 includes strlcpy (and strlcat), musl has both for quite some time as well, but `Makefile.linux` currently unconditionally builds `missing/strlcpy.c` on Linux.

Please consider detecting a system implementation of strlcpy and using that if available.

**Comment by eradman** [comment]
It appears that RedHat [submitted this change](https://sourceware.org/git/?p=glibc.git;a=commit;h=454a20c8756c9c1d55419153255fc7692b3d2199) but _after_ the EL 9 release! This is a shame because it means that RedHat based systems won't get this feature for another 3-4 years.

Thanks for pointing this out, I will wait to see how other projects handle this.

**Comment by eradman** [comment]
Reopening. strlcpy(3) is becoming more widely available (Fedora 39 for example). I'll investigate the best way to detect the system implementation.

**Comment by eradman** [comment]
It appears that the `_DEFAULT_SOURCE` macro was defined for using BSD/misc functions

https://sourceware.org/git/?p=glibc.git;a=commit;h=c688b4196014e0162a1ff11120f6c9516be0c6cb

**Comment by eradman** [comment]
Implemented in commit 1d7e1f39eb833c1955aa2a9c4b65babb25755a2b

**Comment by thesamesam** [comment]
musl still needs `_GNU_SOURCE` or `_BSD_SOURCE` for it for now (until it's in a POSIX release officially), so I'd just use `_GNU_SOURCE` still for now?

**Comment by eradman** [comment]
@thesamesam thanks for tip! I'll add `_GNU_SOURCE` back to the build

**Comment by eradman** [comment]
Alpine Linux 3.19.0 does not seem to need `_GNU_SOURCE`. Is there something Alpine does differently to enable this feature in musl?

```
alpine:~/git/entr$ ldd entr
        /lib/ld-musl-x86_64.so.1 (0x7fc6356bb000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fc6356bb000)
```

**Comment by thesamesam** [comment]
I think `gcc` and `clang` default to `-std=gnu11` (or `gnu17`) which implicitly enables `_GNU_SOURCE`.

If you try with `make CFLAGS="-std=c99"` or similar, you should get a failure. Adding `_GNU_SOURCE` fixes that.

**Comment by eradman** [comment]
Ah exactly right.

In this case I also want to add `-D_GNU_SOURCE` to the configure script. Also should probably using `cc` as the compiler
