### ISSUE TITLE
`/_` marker and quotes.

### ISSUE THREAD

**Issue by head-gardener** [eradman/entr#125]
Command I'm trying to run is
`find . -name 'ps*' | entr -c nvim --headless -c 'PlenaryBustedFile /_ '`
Which doesn't substitute `/_` since the whole vim command in quotes is treated as a single argument. Escaping the quotes will put the filename in but messes up vim's arguments.
Is there some technique that I'm missing or should I just write a makefile for things like that?

**Comment by eradman** [comment]
If you use the shell option, you can get this information from `$0`

```
find . -name 'ps*' | entr -c -s 'nvim --headless -c "PlenaryBustedFile $0"'
```

This works because `entr` adds the filename that changed to the shell args

```
$ sh -c 'echo $0' xyz
xyz
```

**Comment by head-gardener** [comment]
This does work, thank you.
