### ISSUE TITLE
doesn't this force the RLIMIT_NOFILES to be exactly 65536?

### ISSUE THREAD

**Issue by sam-github** [eradman/entr#126]
https://github.com/eradman/entr/blob/817075652ed51d517de261e63311ac63b979d74f/entr.c#L135-L144

It first sets it to the `min(65536, ...)`. then if its less than 65536 it sets it to 65536 .... so that means it can ONLY be 65536 ... which doesn't look like the intention. Am I misreading that?

**Comment by eradman** [comment]
You are correct. The release notes for 5.4 say

>  - Unconditionally try to set soft file limit to 2^16 on MacOS

But this is a very strange way to set a single value! Thanks for pointing this out, I'll neaten this up

**Comment by sam-github** [comment]
One of my co-workers found the limit too small, which is how bumped into this. I can try to figure out from him what he needed, if that's helpful.

**Comment by eradman** [comment]
If he needs more than 65k files then entr might be the wrong tool for the job. I would be interested to know how he hit this limit!

**Comment by eradman** [comment]
I just checked the Linux kernel source: it has almost 82,000 files, so these numbers are possible.

How are you listing files? If you use `ag -l` will skip executables, `.git/`, and so on.

**Comment by sam-github** [comment]
`git ls-files . -z $(git rev-parse --show-cdup) | tr '\0' '\n' | entr -cr "$@"`

**Comment by eradman** [comment]
@sam-github that use of `git ls-files` is clever. I will definately use that pattern!

The reason max_files is limited to 2^16 on Mac is that on arm64 completely bogus values are returned by the OS

```
rlim_cur: 256
rlim_max: 9223372036854775807
_SC_OPEN_MAX: 256
```

Perhaps I should simply bump this to 2^18?

**Comment by eradman** [comment]
Actually, Another limit is in play that `entr` does not account for: `maxfilesperproc`

```
% sysctl kern.maxfiles kern.maxfilesperproc
kern.maxfiles: 30720
kern.maxfilesperproc: 10240
```

@eduaravila how did you raise this value?

**Comment by eradman** [comment]
Based on the behavior of MacOS 13.5, I decided use `kern.maxfilesperproc` as the best aproximation for how many files can be opened. See commit 82aa6f50372a1ff561a3405d1e09ce7a64b5facf.

**Comment by eduaravila** [comment]
Hi @eradman thanks for taking the time to fix it! 

I do remember doing the following:
`6881  sudo sysctl kern.maxfiles=9999999 kern.maxfilesperproc=9000000`

It's worth mentioning that I followed this tutorial to raise some of the other limits: https://developer.apple.com/forums/thread/735798

**Comment by eradman** [comment]
I updated http://eradman.com/entrproject/limits.html with the `sysctl` commands for setting this limit.
Thanks all for bringing this topic back to my attention. Support for Mac OS has proven to be a moving target!
