### ISSUE TITLE
Feature request: provide a way to debounce triggers

### ISSUE THREAD

**Issue by jaresty** [eradman/entr#127]
It would be really cool if there were some way to debounce triggers. Imagine that you are making lots of quick changes to several files and you want to do something when those files change that is expensive, like uploading to a server. It would be nice if you could set a debounce of say 5 seconds that would queue up and trigger after 5 seconds had passed, passing all files that had changed in that time.

What do you think?

**Comment by jaresty** [comment]
It's not just a delay that I'm looking for- I also want it to aggregate the results. Here's a concrete example. 

Imagine that I'm changing files a, b, and c in quick succession and then I want to trigger an upload to a server. 

Currently, entry will trigger three times - once for each file. 

What I'd like is for it to trigger once and pass all three files as arguments to the command I provide. 

Does that make sense?

**Comment by eradman** [comment]
That makes sense, except `entr` does consolidates events that occur while executing a command. (Actually it drops them, but same effect.)

Try this

```
touch a b c
ls a b c | entr -p -s 'sleep 6; echo files changed; ls -l a b c'
```

Then in a second window update these files

```
for f in a b c; do date > $f; sleep1; done
```

You _should_ see that the utility was only executed once

**Comment by eradman** [comment]
No `/_` can't be used for this purpose. It's a fair question though, see my answer in https://github.com/eradman/entr/issues/67#issuecomment-783666658

**Comment by jaresty** [comment]
I see... so the idea would be to use `entr` to trigger and then `make` to trigger based on things that changed.  I think that could work.

**Comment by eradman** [comment]
Excactly. The design of `entr` is entirely based on detecting conditions that should trip and execution. This means it reopen files that were replaced (so that it can watch them), but it also discarding events that it consideres to be redundant.

I feel stronly that keeping track of things that have changed or are out of date is the responsibility of other tools. Although I do wish tools such as `make` was easier to use...

**Comment by jaresty** [comment]
Understood.  Thank you!
