### ISSUE TITLE
`entr` apparently don't work when called from a Makefile task

### ISSUE THREAD

**Issue by joeljuca** [eradman/entr#129]
I got a small problem with entr. For some reason, it doesn't seem to rerun tests when I use entr from a Makefile task.

Here's the Makefile (non-related content already stripped):

```Makefile
.PHONY: test.watch

test.watch:
	ls -1 $(find -E lib test -regex '.*exs?$') | entr -cr mix test
```

This is an [Elixir](https://elixir-lang.org) project, so file are named `*.ex` and `*.exs`. The `find` command works fine, and if I run the snippet outside Makefile it works pretty well, but if I try to run it as a Makefile tas (`make test.watch`), it runs once but does not rerun when files change.

Am I missing something obvious here?

> _PS: FWIW, [I wrote an article about entr on DEV](https://dev.to/joeljuca/meet-entr-the-standalone-file-watcher-42a) today and shared the text and project in some communities I participate. Nice project! :)_

**Comment by eradman** [comment]
What is the goal of using `ls -1 $(find ...)` instead of just `find ...`?

Be careful to escape `$`: run subshell using `$$(...)`

**Comment by joeljuca** [comment]
The `ls` piece was left there just to have one file per line (something I was not entirely sure was needed or not; good to know it isn't).

I was having the the following error when using it outside `$( ... )`:

```Makefile
.PHONY: test.watch

test.watch:
	find -E lib test -regex '.*exs?$' | entr -cr mix test
```

```
$ make test.watch
find -E lib test -regex '.*exs? | entr -cr mix test
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [test.watch] Error 2
```

The `$'` part was being interpreted as a variable. When I removed the wrapping quotes it worked just fine (the initial problem was gone).

Thanks for the help!

**Comment by eradman** [comment]
You're welcome! make(1) is a valuable tool (I use it all the time), but it has some sharp edges.

Thanks for the link to the article you posted. News fragments and short articles like this really do help people find useful tools and techniques.
