### ISSUE TITLE
Git tags are not signed

### ISSUE THREAD

**Issue by ottok** [eradman/entr#133]
Hi!

While working on Debian import of Entr 5.5 I noticed that release tag is not signed:

```
$ git show 5.5
tag 5.5
Tagger: Eric Radman <ericshane@eradman.com>
Date:   Fri Nov 17 02:22:21 2023 -0500

entr-5.5

- Report correct error if open(3) fails
- Use kern.maxfilesperproc to determine file open limit on MacOS

$ git tag --verify 5.5
object 8ed69ace080a73ff923c20f01a3ded28df3b4e1c
type commit
tag 5.5
tagger Eric Radman <ericshane@eradman.com> 1700205741 -0500

entr-5.5

- Report correct error if open(3) fails
- Use kern.maxfilesperproc to determine file open limit on MacOS
error: no signature found
```

See https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work on how to sign tags is you want to do it in the future to help maintain software supply chain security.

Thanks!

**Comment by eradman** [comment]
Are you suggting that commits be signed or the tag itself?

This was the first release I cut using an annotated tag

```
$ git for-each-ref refs/tags | tail  -n3
ced4b72c9b78522113a23b0426f20877af358c62 commit refs/tags/5.3
a4259d243c6306fb4754053b32268e34e290d94e commit refs/tags/5.4
dfec472ddad71ed9e129628bd9716cc854d8ab86 tag    refs/tags/5.5
```

I do publish checksums:

https://eradman.com/entrproject/code/CHECKSUMS.txt

**Comment by ottok** [comment]
Yes, I am referring to signed git tags. If you run `git config --local tag.gpgSign true` in your local clone, your future tags will be automatically signed. Alternatively you can always run `git tag` with `--sign` next time you do tags.

**Comment by eradman** [comment]
Thanks for the tips. I usually avoid gnupg because when it fails it is difficult to debug. 

```
$ git tag -s -a 0.0.3

error: gpg failed to sign the data:
[GNUPG:] KEY_CONSIDERED 519151D83E83D40A232B4D615C418B8631BC7C26 2
[GNUPG:] BEGIN_SIGNING H8
[GNUPG:] PINENTRY_LAUNCHED 17459 curses 1.2.1 - st-256color :0 - 1000/1000 0
gpg: signing failed: Inappropriate ioctl for device
[GNUPG:] FAILURE sign 83918950
gpg: signing failed: Inappropriate ioctl for device

error: unable to sign the tag
The tag message has been left in .git/TAG_EDITMSG
```

If you have time, ping me over email and we'll see if we can get it working.

**Comment by ottok** [comment]
Thanks for considering the request. I will follow-up by email.
