### ISSUE TITLE
execute utility only once

### ISSUE THREAD

**Issue by bjarthur** [eradman/entr#14]
is there a way to use `entr` to simply block execution of a script until a file has changed?  right now i'm using this polling strategy, but would prefer an interrupt:

`while <file-has-not-changed> ; do sleep 1 ; done`

i was hoping that `ls foo | entr -pn true` or similar might work, but `entr` doesn't exit.  is there a work around?  if not, how easy would it be to add a new flag to `entr`?

thanks for the great utility!

**Comment by eradman** [comment]
Indeed there is a workaround

    entr -pn sh -c 'kill $PPID'

or

    entr -pn -s 'kill $PPID'

I have been asked for "one-shot" flag before... If I don't do that there should probably at least be an example in the man page.

**Comment by eradman** [comment]
This is a reoccurring question, so I added this to the man page and README file in commit 651c573

**Comment by eradman** [comment]
I implemented a one-shot option (`-z`) in commit 3699800. For more details see issue #23
