### ISSUE TITLE
Is there an easy way to print out the time that `entr` ran the last command?

### ISSUE THREAD

**Issue by scottchiefbaker** [eradman/entr#143]
It would be great if there was a `--date` option for `entr` that would print the datetime the last invocation ran. Knowing the datetime informs me if the output I'm seeing is current.

I've tried a couple of things and can't come up with an obvious solution:

```
ls /tmp/x.pl  | entr -s -c '/usr/bin/date; perl /tmp/x.pl'
```

This works but it outputs "bash returned exit code 0" after every iteration. It's also not particularly intuitive. Having a built in option in `entr` would be ideal.

**Comment by scottchiefbaker** [comment]
I'm thinking a header at the top of the screen similar to how `watch` does it.

**Comment by eradman** [comment]
The next release of entr will include [status filters](http://eradman.com/entrproject/status-filters.html) which will allow you to customize the status line.

This is enabled using the `-x` flag, (or `-xx` to run system commands). Write and define custom status output in `$HOME/.entr/status.awk`. The most simple thing you could do is run the `date` command, but any other formatting is possible

```awk
{
  system("date")
}
```

Try compiling `entr` from source and see how this feature works for you.

**Comment by scottchiefbaker** [comment]
@eradman I compiled the new version and it does work as you described above. It does still feel like a lot of extra work and knowledge just to add the date to the output. I feel like that would be a pretty common thing people would want to know.

**Comment by eradman** [comment]
I stalled for a long time on implementing a such a general approach in part because I thought something similar--surely there are a few standard status messages people would want!

This turned out not to be the case--which is the reason I skipped over more obvious solutions such as a status format string.

If you want to use the status filter all the time, you may want to alias `entr` in your `.profile`

```
alias entr='entr -xx'
```
