### ISSUE TITLE
Include workspaces

### ISSUE THREAD

**Issue by Jopp-gh** [eradman/entr#145]
well, so far I've seen a bunch of similar tools like incron, fswatch and yours.

Probably there are even more tools of this kind I don't know. Problem is, all these tools do more or less  the same (sorry for being so lapidary) but none of them cares of workspaces. How about:

1. switch to workspace `<name>` or `<id>`
2. workspace `<name>` or `<id>` triggers a specific script or predefined conditions

predefined conditions:
- bluetooth on / off
- dvd/cd detected
- media mounted / unmounted
- wireless on / off
- internet on / off
- some app on / off

So workspaces would get a new meaning, instead to be just another space to "fill" like a trashbin

**Comment by eradman** [comment]
Do you have in mind something like [hotplug(8)](https://man.openbsd.org/hotplugd.8) for Linux?

**Comment by eradman** [comment]
I have a hard time imagining how a cross-platform "workspace-event" tool could be built, since each OS has completely different mechanisms available, and this requires cooperation between kernel and userspace.

Closing, since `entr` only deals with file system events.
