### ISSUE TITLE
Commands run twice with the -d flag

### ISSUE THREAD

**Issue by saint-thomas-more** [eradman/entr#146]
Built entr from source at a7f1f0c using CheckInstall on Linux
The following gives two notifications after adding a file:
```sh
while sleep 1 ; do ls -d ~ | entr -d notify-send 'test' ; done
``` 
And the following gives one as expected:
```sh
while sleep 1 ; do ls ~ | entr notify-send 'test' ; done
```

**Comment by eradman** [comment]
What method are you using the create the file? Try setting the environment variable `EV_TRACE=1` and reply with the output.

**Comment by saint-thomas-more** [comment]
Okay, I've now realized I'm stupid and forgot to use `-p` because `-d` restarts entr after each operation and therefore executes the command twice in a row. Sorry ^_^"
