### ISSUE TITLE
Feature Request: execute given command only on regexp match

### ISSUE THREAD

**Issue by thyseus** [eradman/entr#15]
Hi,

in modern tests frameworks like rspec, phpunit, codeception, django, whatever it is common to have the application code separated from the test code. We basically have this structure:

app/  <-- application code
tests/ <-- test code

When i want to automate the test execution during the save of an file, i need to watch _both_ the test and the application file. I only want to run the tests file though.

So doing a

```
ls **/*.php | entr vendor/bin/codecept run unit /_
```

would try to execute also the application code instead of only the test code.

My Question: is there already a solution to this Problem ? If not,
My Proposal: add an option to match the _absolute path_ of the changed file to a regexp.

Example:

entr --only-execute-on-match /tests\/ 

This would mean that entr only executes the given command when the absolute path matches the given regular expression and this would solve the problem:

```
ls **/*.php | entr --only-execute-on-match /tests\/ vendor/bin/codecept run unit /_
```

Watching two files with entr like:

app/DispatchOrder.php
tests/DispatchOrderTest.php

would only execute the DispatchOrderTest.php file on the change of _any_ file because the regexp "tests/" needs to match.

what are your ideas about this?

**Comment by eradman** [comment]
The `/_` was not intended to give you the ability to make choices based on the file that changed; it was conceived as shorthand for watching a single file

    ls run.sh | entr /_

The reason for this is that the "leading edge" (first file to change) is not deterministic (switching a branch in git for example).

But I see what you're trying to do.  This can be emulated with some indirection

    ls **/*.php | entr ruby -e 'exec(ARGV[0]) if ARGV[0] =~ /tests/' /_

I'll think further on how I would try to solve this

**Comment by thyseus** [comment]
Hey eradman,

thanks a lot for your quick reply. I see your point, and your solution it is great; i can incorporate in my use case.

Thinking about it, one would need to do a "mapping" of the Test file in relation to the Code File. Different test frameworks do have different implementations. For example, in go(lang) it is common to have the test file directly beneath the code:

main.go
main_test.go

which would make it easy, testing frameworks like codeception does not have a "rule", - your test structure can differ completely from your code structure. Using PHPStorm, you can "map" the codeception tests to your code structure in the "runner execution config"; Rubymine also has a feature like that; but i doubt that we can find a "lightweight" solution into entr. 

Probably it should stay the "one tool, one purpose" (unix philosophy(tm)) tool it is, implementing such a mapping _MAY_ be overkill. 

What is your opinion ? :)

**Comment by eradman** [comment]
Limiting the scope of what `entr` does (in keeping with unix philosophy) is definitely my goal.

I think the right approach is to use Make or some other build tool that can react properly to the files that changed. Here is an example:

    all: test.mk
    
    test.mk: tests/*.php
            tests/run_tests
            touch $@

I use variations of this. It works because make(1) keeps track of timestamps, and if a dependency is newer than the target (`test.mk`) then it will run it again.
