### ISSUE TITLE
no stdin should watch current directory recursively

### ISSUE THREAD

**Issue by verhovsky** [eradman/entr#153]
```bash
$ entr ./run_tests.sh
release: 5.6
usage: entr [-acdnprsxz] utility [argument [/_] ...] < filenames
```

Instead of a usage message it should watch all files and directories in the current directory. That way I have to type less to use entr for the simple case.

**Comment by eradman** [comment]
I have considered adding this capability, but inevitable my conclusion is that an external utility is best suited for a vast range of use cases.

Listing "all files and directories" in the current working directory is simple enough, but what should be excluded?

- `.git/`
- files listed in `.gitignore`
- temporary files
- binary files

These are all considerations taken into account by `ag -l`.

As for default functionality, this can often be solved using shell aliases, such as

```bash
alias _entr='ls -d * | entr'
```
