### ISSUE TITLE
docker for mac patch getting old

### ISSUE THREAD

**Issue by matti** [eradman/entr#16]
The patch file version is http://eradman.com/entrproject/patches/entr-3.9-docker while the entr is at 4.x

Currently it does apply and the binary seems to work, see https://github.com/matti/docker-entr/blob/master/build/ubuntu/Dockerfile#L13-L17

Also, could it be possible to include the patch in entr and have the behaviour available as an option?  I think I've wasted something like an 2 hours trying to figure out what was wrong with docker-for-mac and entr - just found out https://github.com/eradman/entr/issues/3 by accident

**Comment by eradman** [comment]
I was hoping the patches would serve to put some pressure on the Docker project to finish implementing support of inotify. So far they're not interested.

Maybe I should support this using an environment variable `BROKEN_INOTIFY_WORKAROUND`?

**Comment by matti** [comment]
sounds good!

**Comment by eradman** [comment]
Commit e158c36 enables the compatibility mode for platforms with deformed inotify support by setting ENTR_INOTIFY_WORKAROUND

**Comment by eradman** [comment]
This was included in the latest release:

https://github.com/eradman/entr/releases/tag/4.4

**Comment by matti** [comment]
what's the implication for platforms where inotify support is not broken, eg. can I just set this on for both linux and mac?

**Comment by eradman** [comment]
On Linux, where Docker/inotify support works, you can set `BROKEN_INOTIFY_WORKAROUND` but some conditions will cause `entr` will execute the utility when it shouldn't have.

So there is no harm in setting it as long as you're okay with with behavior that is occasionally not correct. In most cases you probably won't notice.

**Comment by matti** [comment]
where could I learn more about these rare cases?

**Comment by eradman** [comment]
I can't say under what conditions entr will misbehave... the symptom is that that inotify incorrectly reports `IN_MODIFY` instead of the the real event. The full list from `sys/inotify.h` are:

```
#define IN_ACCESS·       0x00000001·    /* File was accessed.  */
#define IN_MODIFY·       0x00000002·    /* File was modified.  */
#define IN_ATTRIB·       0x00000004·    /* Metadata changed.  */
#define IN_CLOSE_WRITE·  0x00000008·    /* Writtable file was closed.  */
#define IN_CLOSE_NOWRITE 0x00000010·    /* Unwrittable file closed.  */
#define IN_CLOSE·        (IN_CLOSE_WRITE | IN_CLOSE_NOWRITE) /* Close.  */
#define IN_OPEN··        0x00000020·    /* File was opened.  */
#define IN_MOVED_FROM·   0x00000040·    /* File was moved from X.  */
#define IN_MOVED_TO      0x00000080·    /* File was moved to Y.  */
#define IN_MOVE··        (IN_MOVED_FROM | IN_MOVED_TO) /* Moves.  */
#define IN_CREATE·       0x00000100·    /* Subfile was created.  */
#define IN_DELETE·       0x00000200·    /* Subfile was deleted.  */
#define IN_DELETE_SELF·  0x00000400·    /* Self was deleted.  */
#define IN_MOVE_SELF·    0x00000800·    /* Self was moved.  */
```

**Comment by matti** [comment]
https://github.com/matti/entr/commit/4f68b0d315fd5f165ffbf87be232810873c88c16

I enabled this as default so that I can:

```
COPY --from=mattipaksula/entr:4.4-friendly /entr /usr/local/bin
```
