### ISSUE TITLE
New release from master ?

### ISSUE THREAD

**Issue by pre** [eradman/entr#17]
Latest release is v4.3 from September 2019 (last year!) 

There are good commits waiting in master, especially the Docker for Mac workaround https://github.com/eradman/entr/commit/e158c367b6ef9a473ed7a7d030f4bca695592554 

How about releasing v4.4 from the current state of master? Thank you !

**Comment by eradman** [comment]
Agreed; I tagged a new release

https://github.com/eradman/entr/releases/tag/4.4
