### ISSUE TITLE
Please add a shortcut for passing stdin from a file

### ISSUE THREAD

**Issue by jaresty** [eradman/entr#2]
I often find myself using entr to write helper scripts that work on files. I would love it if I could write those scripts to read from stdin and write to stdout, but there isn't a really easy way to do that with entr since it would receive shell redirection if it was done as an argument to the cli itself. It would be nice if there were a built in entr flag to tell it to send stdin to a command from a specific file to make this use case easier.

**Comment by eradman** [comment]
Can you provide an command line example of what this feature might look like?

**Comment by jaresty** [comment]
Here's an example:

`entr -i path/to/file cmd` would pass the file contents of `file` to the command `cmd` via stdin.

**Comment by eradman** [comment]
I don't think you need an additional flag for this, would standard shell redirection work?

    entr cmd < path/to/file

**Comment by jaresty** [comment]
I believe that results in entr itself getting the input. I imagine you
would not be able to press space to rerun the command for example. I'm not
able to double-check though since I'm away from my computer this week. Am I
mistaken?

2019年7月6日(土) 13:17 Eric Radman <notifications@github.com>:

**Comment by eradman** [comment]
Keyboard input to `entr` works in the example I provided; in fact on POSIX these two function identically

    cat file | entr cmd
    entr cmd < file

But I see I misunderstood what you are after! All you have to do is run the command in a shell:

    ls *.X | entr -s 'cmd < input'

Using this pattern you can pipe input and output to the utility you are running

**Comment by jaresty** [comment]
I see. The shell does indeed work for passing stdin--is there any way using the shell to pass the name of the file that changed? I tried using `\_` but it didn't seem to work.

**Comment by eradman** [comment]
Yes there is--when running a shell use `$0` to see the file that changed. (I should document that)

**Comment by jaresty** [comment]
Perfect-thank you!

**Comment by eradman** [comment]
I updated the man page to document the use of `$0` with the `-s` flag in commit f25931d

**Comment by jaresty** [comment]
Thanks!
