### ISSUE TITLE
I can't get get the version og `entr`

### ISSUE THREAD

**Issue by TJProgrammer** [eradman/entr#22]
Hello!

I tried get the version of entr, but I can't.
My script:
```
f_test_entr_version(){
  local version
  version="$(entr - | cut -d ' ' -f 2 | head -n 1)"
  f_compare_version "$G_ENTR_VERSION" "$version"
  return $?
}
```
What I am doing wrong?

A suggestion: add a `-h` and/or `-v` option to output help or/and version.

**Comment by eradman** [comment]
Try 

    entr 2>&1 | awk '/release:/ { print $2}'

What is the use case for testing this version number?

**Comment by TJProgrammer** [comment]
Thanks!

`version="$(entr 2>&1 | cut -d ' ' -f 2 | head -n 1)"` works great!

The use case is in development state an entire team get this program in the same or superior version.
