### ISSUE TITLE
Entr does not restart given command on crash

### ISSUE THREAD

**Issue by pre** [eradman/entr#23]
In this case, I'm using `entr` to restart a Ruby process when source files change. 

Problem: `entr` does not restart the process when the Ruby process crashes (it's a development environment after all).

My environment is minikube in MacOS. Live reloading works using the entr inode workaround.

Is the problem in my configuration or what could cause this?

<img width="1675" alt="2020-02-18 at 11 52" src="https://user-images.githubusercontent.com/63895/74725922-4579fe80-5247-11ea-921e-950fd52e187d.png">

Entrypoint:
```bash
#! /usr/bin/env bash

set -euo pipefail

_term() {
 >&2 echo "TERM"
 exit 0
}

trap "_term" TERM

OPERATOR="${1:-}"
COMMAND="bin/operators/${OPERATOR}"

if [[ -z "${OPERATOR}" ]]; then
  echo "Error: Missing parameter operator name."
  echo "Usage: $0 operator_name"
  exit 1
elif [[ ! -x "${COMMAND}" ]]; then
  echo "Error: Command '${COMMAND}' is not executable."
  exit 1
fi

if [[ "${ENV}" = "development" ]]; then
  export ENTR_INOTIFY_WORKAROUND="yespls"
  (
    while true; do
      set +e
        find . | entr -rd "${COMMAND}"
      set -e
    done
  ) &
else
  set +e
    "${COMMAND}" &
  set -e
fi

wait $!
```

**Comment by matti** [comment]
hey @pre I'm also noticing this behavior - I tested with following muna.rb:

```
puts "exiting with an error"
exit 1
```

and indeed entr just hangs - if I save the muna.rb again it reloads it, prints and exits

**Comment by matti** [comment]
```
while true; do
  set +e
    find * | entr -dr ruby clusterapi.rb &
    wait $!
  set -e

  echo "exited"
  sleep 1
done
```

it never says "exited", only restarts the ruby process after I save again

**Comment by eradman** [comment]
`entr` does not try to restart the process automatically. From the man page:

```
     -r      Reload a persistent child process.  As with the standard mode of
             operation, a utility which terminates is not executed again until
             a file system or keyboard event is processed. ...
```

@pre, in the example you listed you already have a `while` loop, maybe the simplest solution is to simply self-terminate if the `$COMMAND` exits:

```
find . | entr -rds "${COMMAND}; kill $PPID"
```

**Comment by pre** [comment]
Unfortunately adding `-s` and `kill $PPID` makes no difference. If the process crashes (or exits with error), `entr` just hangs and the `kill $PPID` is not executed.  

The problem can be reproduced using this minimal use case: https://github.com/eradman/entr/issues/23#issuecomment-588276654

If I save a file which is being watched, then `entr` will restart the process. Manually triggering a file event is cumbersome in a development flow where crashes are frequent (and you notice them) - as unless the whole project is being watched, you'll need to find, open & save a file which is being watched. In this case it'd be faster to just restart the whole process, but then again, it is inside minikube so that'd be even more work.

**Comment by eradman** [comment]
There was an error in my previous suggestion. We need to escape `$PPID`

    find . | entr -rds "${COMMAND}; kill \$PPID"

**Comment by pre** [comment]
Escaping is not the problem.  The problem is that `entr` hangs and the `kill` (or any command following `entr`) is not executed at all. 

I think the problem would be fixed if `entr` would exit when the tracked process exits. 

Here's a repro:

test.sh
```bash
#!/usr/bin/env bash

# "boom" should be displayed in a loop, but it's only displayed once
echo "boom"
exit 1
```

entrypoint
```bash
while true; do
  set +e
    echo 'ok'
    find . | entr -rds "/test.sh"; echo 'This is not executed'
  set -e

  sleep 1
done
```

This will output 
1) "ok"
2) "boom"
3) But it does not output "This is not executed"

**Comment by eradman** [comment]
`entr` is not "hanging", it's waiting for file system events. I think you're asking for a new feature. @pre, which of these most closely matches what you are looking for?

1. An option to start the subprocess again if it exits for any reason
2. A "one-shot" option which causes `entr` to exit when the child process exits
3. An option to conditionally terminate based on the child exit code

**Comment by pre** [comment]
I think option 2 (A "one-shot" option which causes entr to exit when the child process exits) gives the most flexibility, since the control loop (`while true; .. sleep ; done`) and `find` are are already outside of the `entr` process.

**Comment by eradman** [comment]
I agree;  a "one-shot" option is the most general, and will be useful in a variety of cases. I'll propose a change that implements this

**Comment by eradman** [comment]
I implemented a one-shot option (`-z`) in commit 3699800

**Comment by eradman** [comment]
A few comments about this new feature

* I don't have a good reason for picking `-z`, but feels okay at the command line
* `entr` will will still restart the utility with `-r`, but this relies on preemption by `SIGCHLD`. So far this seems reliable (Tested on OpenBSD, Alpine on MacOS)

**Comment by pre** [comment]
Thanks! I tried it out and `-z` seems to work as expected.

I noticed a typo in the docs ( "agin" ): https://github.com/eradman/entr/commit/3699800a691c9fc96f8fbb21cd46703697294955#diff-ad6bee5c78eebc7bc0f01e15f30c909bR97

**Comment by eradman** [comment]
Thanks for catching the typo. So far I'm happy with this change, but I'm going to leave this ticket open for at least a week while we try it out.

**Comment by eradman** [comment]
So far this new flag seems good. It will be in the next release
