### ISSUE TITLE
Please add Ubuntu Snap package to get latest version of entr

### ISSUE THREAD

**Issue by Donboscow** [eradman/entr#25]
Please add Ubuntu Snap package in htps://snapcraft.io to get the latest version of entr. Here is some resources available htps://snapcraft.io/build

**Comment by eradman** [comment]
Packaging software for a particular platform requires careful attention to the conventions for a given platform; for this reason I don't typically set up package builds. Other people have proven to be much better at this.

I'll leave this ticket open for a little while in case someone with some experience with Snap packages would like to contribute.

**Comment by eradman** [comment]
Closing since nobody flagged this as a task they would take care of
