### ISSUE TITLE
entr + gnu parallel != success

### ISSUE THREAD

**Issue by cameron** [eradman/entr#26]
entr doesn't seem to get file events when run by parallel... 

More details in the repro repo: https://github.com/cameron/entr-parallel-bug-sscce

**Comment by eradman** [comment]
This probably doesn't work because `parallel` is closing STDIN, so `entr` is being suspended with the signal `TTIN`. You can see
the process state with `ps -x`. (`T` means suspended)

Try running entr with `-n`

**Comment by cameron** [comment]
I knew there was some nix concept I was missing that would make this
legible. Ty for the tip.

**Comment by cameron** [comment]
Success! Thanks again, and again and again for the wonderful tool that has been part of my everyday coding life for the years :)

**Comment by eradman** [comment]
Cool! Glad it worked.
Also delighted to hear from people who were helped by this tool
