### ISSUE TITLE
entr fails with regular user

### ISSUE THREAD

**Issue by KyleMcB** [eradman/entr#27]
This probably isn't a problem with entr but a problem with linux administration. Any help would be appreciated.
I recently switched to fedora for my desktop, and now entr isn't working for me.
user watches:

~/D/entr (master|✔) $ cat /proc/sys/fs/inotify/max_user_watches
8192

example run:
~/D/entr (master|✔) $ ls | entr -s "echo 'hi'"
entr: Unable to allocate memory for kernel queue. Please consult http://eradman.com/entrproject/limits.html

However when run as root
~/D/entr (master|✔) [1] $ ls | sudo entr -s "echo 'hi'"
hi
bash returned exit code 0

I would rather not run all my development tests as root. Any ideas how to get it to work as a regular user?

**Comment by KyleMcB** [comment]
Oh and make test passes all tests

**Comment by KyleMcB** [comment]
It seems to be working now. I really wish I knew what happened, but oh well.

**Comment by eradman** [comment]
Are you running entr-4.4?

**Comment by KyleMcB** [comment]
yeah, I'm using 4.4. I used the one installed from dnf. then removed it and built form source. They both had that problem. Except it works fine now.

**Comment by eradman** [comment]
For older versions there are some common causes, but on 4.4 getting that error message is surprising. All the best!

**Comment by julibeg** [comment]
I just had the exact same issue: `entr` would only work when run as `sudo`. However, after rebooting it worked as regular user as well. `make test` passed and `cat /proc/sys/fs/inotify/max_user_watches` gave `8192`. No idea, what the reason might be.
