### ISSUE TITLE
entr -a not behaving as I'd expect

### ISSUE THREAD

**Issue by cameron** [eradman/entr#28]
I'm not sure this is a problem on entr's end, but:
`$ touch watchme; ls watchme | entr -a echo changed`
`$ echo "asdf" >> watchme; echo "asdf" >> watchme; echo "asdf" >> watchme;`
results in 1-2 invocations of `echo changed` as opposed to the expected three. 

I discovered this while trying to use entr as a last resort for running one command per line written to a log file (was having issues with pipe buffers and finally got it sorted using stdbuf). 

Is it possible the shell is buffering the writes? 

_Goes and tries `stdbuf -o0 echo asdf >> watchme;` x3..._

Sure enough! Will submit and close just in case anyone else...

**Comment by eradman** [comment]
Indeed, I get a fair number of bug reports which are the result of people running into nuances or surprising features of a POSIX environment. Most things like this make sense, but you have to run into these things to learn them!
