### ISSUE TITLE
Known issues w/ docker-for-mac?

### ISSUE THREAD

**Issue by ItsLeeOwen** [eradman/entr#3]
entr is able to detect filechanges locally on the host, but not within the docker container.  I'm using a mounted volume for the source files, and can see that `find .` is passing files to `entr`, which successfully runs make once, but no file changes are detected.

25 of 25 tests pass when installing entr, but there is output mentioning something missing:

```sh
Step 6/26 : RUN cd ./entr && ./configure && make test && make install
 ---> Running in 0055d55f74d0
cc  -D_GNU_SOURCE -D_LINUX_PORT -Imissing -DRELEASE=\"4.3\" missing/strlcpy.c missing/kqueue_inotify.c entr_spec.c -o entr_spec
cc  -D_GNU_SOURCE -D_LINUX_PORT -Imissing -DRELEASE=\"4.3\" missing/strlcpy.c missing/kqueue_inotify.c entr.c -o entr
Running unit tests
25 of 25 tests PASSED
install entr /usr/local/bin
install -m 644 entr.1 /usr/local/share/man/man1
```

I've tried both of the following commands.

```sh
find -d ./src | entr -d make
```
```sh
ls -d ./src/**/* | entr -d make
```

**Comment by ItsLeeOwen** [comment]
Looks like there's some long running discussion that may be related here:
https://github.com/docker/for-mac/issues/1802

**Comment by eradman** [comment]
This is a long-standing problem in Docker; here is one of the many tickets that detail the problem: https://github.com/docker/for-mac/issues/896

You can apply the following source patch as a workaround:

    wget http://entrproject.org/patches/entr-3.9-wsl
    patch -p1 < entr-3.9-wsl
    ./configure
    make install

**Comment by ItsLeeOwen** [comment]
Thank you, the patch worked.  We should probably update the README to include a mention of this for docker-for-mac, I didn't try that because it's only suggested for Windows.

**Comment by eradman** [comment]
Good suggestion; in commit e38e86f documented this patch for Docker on Mac.

**Comment by DarrenTsung** [comment]
Worth noting that there is a workaround in `entr` via the `ENTR_INOTIFY_WORKAROUND` flag referenced in #16:
https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux

^For people stumbling on this via search and missing the note in the README.

**Comment by MarceloPrado** [comment]
Just adding my two cents here, I can confirm the `ENTR_INOTIFY_WORKAROUND` fixes the issue on Docker for Mac. In my case, I was running a container with a mounted volume and `entr` wouldn't pick any file changes. After setting the variable, things started to work as expected.

Something to be aware (I've spent a couple of minutes until I figured this out): **make sure you're not installing `entr` from `apt-get`** in your Dockerfile, but downloading from this github repository.

If it helps, here's the related `Dockerfile` steps:

```
# File watcher for running tests on watch mode
RUN git clone https://github.com/eradman/entr && cd entr/ && ./configure && make test && make install

# Fix file watcher on Mac (see: https://github.com/eradman/entr/issues/3)
ENV ENTR_INOTIFY_WORKAROUND 1 
```

**Comment by eradman** [comment]
Thanks @MarceloPrado. Looks like spinning up Debian docker image (10.4) provides entr-4.1, which is doesn't have this workaround

Debian "bullseye" and "sid" have a package that will work

https://packages.debian.org/sid/entr

**Comment by MarceloPrado** [comment]
You're right @eradman .
For notice, I'm using the `python:3.8` image.

Also, thanks for your work on this project. It's a great package. I particularly liked the idea of using it as a pipe operator, really neat!
