### ISSUE TITLE
can I reload brower but not focus it? 

### ISSUE THREAD

**Issue by zdmgmail** [eradman/entr#31]
can I reload brower but not focus it? 

```
ls *.html | entr reload-browser chrome
```

always want continue edit

**Comment by eradman** [comment]
What OS are you using?

**Comment by zdmgmail** [comment]
> What OS are you using?

```
linux 

~ » uname -a                                                                             zdm@ar
Linux ar 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux
```

**Comment by eradman** [comment]
I made the following modifications
to http://eradman.com/entrproject/scripts/reload-browser

    +               cw=$(xdotool getwindowfocus -f)
    ...
    +               sleep 0.5
    +               cd=$(xdotool windowfocus $cw)

Download the script again and see if this helps

**Comment by zdmgmail** [comment]
> I made the following modifications
> to http://eradman.com/entrproject/scripts/reload-browser
> 
> ```
> +               cw=$(xdotool getwindowfocus -f)
> ...
> +               sleep 0.5
> +               xdotool windowfocus $cw
> ```
> 
> Download the script again and see if this helps

Perfectly solved !! thanks

**Comment by eradman** [comment]
Super! This script is a best effort, but really useful when it works.

**Comment by eradman** [comment]
There was conversation about this on an old bug filed against chromium
https://bugs.chromium.org/p/chromium/issues/detail?id=393145
