### ISSUE TITLE
`touch`ing a watched file doesn't trigger execution

### ISSUE THREAD

**Issue by maiamcc** [eradman/entr#32]
Given invocation `echo '.restart' | /entr -rz util.sh`, I see:

1. `echo foo >> .restart` (i.e. appending to the file) triggers the utility (as expected)
2. `echo foo > .restart` multiple times in a row (i.e. overwriting the file with the same contents as it had before) triggers the utility(as expected)
3. `touch .restart` does NOT trigger `util.sh`, even though the timestamp on the file is updated.

Case 3 is surprising to me: is it expected that `touch`ing a watched file doesn't trigger the utility? If so, what's the logic here?

**Comment by eradman** [comment]
`entr` normally ignores file metadata changes, except in when the mode bits are changed.

This utility tries very hard not to react until file changes are complete. If you were to download a file for example, the file metadata is changing, but `entr` does not run the utility until the kernel sends `NOTE_WRITE` (BSD/MacOS) or `IN_CLOSE_WRITE` (Linux).

How do deal with your use case?  You could just write a file with a single character

    echo > .restart

or maybe make it useful

    date > .restart

**Comment by maiamcc** [comment]
Aah okay, that explanation makes sense, as does the workaround. Thanks!

**Comment by eradman** [comment]
NP! For sure people occasionally hit this corner case, but a workaround is all I can suggest.
