### ISSUE TITLE
suspended problem

### ISSUE THREAD

**Issue by zdmgmail** [eradman/entr#34]
I use entr in terminal or vim,  want to exit entr when close vim or terminal 

```sh
ls * | entr reload-browser chrome &> /dev/null &
```

if I run this command in terminal

```
[1]  + 123095 done                    ls --color=tty * |
       123096 suspended (tty output)  entr reload-browser chrome &> /dev/null
```

refresh one time  and then doesn't work

if I run this command in vim: 

```
:! ls * | entr reload-browser chrome &> /dev/null &
```

always work, even I exit vim 

can I Run the program in the background and exit when vim or terminal exit?

**Comment by zdmgmail** [comment]
```
~/Code/bootstrap » nvim --version                                        127 ↵ zdm@ar
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

```
~/Code/bootstrap » uname -a                                                    zdm@ar
Linux ar 5.6.5-arch3-1 #1 SMP PREEMPT Sun, 19 Apr 2020 13:14:25 +0000 x86_64 GNU/Linux
```

**Comment by eradman** [comment]
Using the `-n` option should solve this.

Normally `entr` opens a TTY for keyboard input, but it's being suspended with the `TTOU` signal.

**Comment by porky11** [comment]
I also had this problem. Good, that I found this :)
