### ISSUE TITLE
Question: can I use it to upload files as they get created?

### ISSUE THREAD

**Issue by d33tah** [eradman/entr#41]
Sometimes I run the following command or something similar:

```
stdbuf -o 0 inotifywait -m . --format='%f' -e close_write | \
    xargs -n1 -P20 -I{} bash -c 'aws s3 cp {} s3://bucket/{}'
```

Does entr support this use case?

**Comment by eradman** [comment]
`entr` does not have a mode to emit the name of every file that changes, but you can monitor for changes to a directory and use another tool to find an sync files

```
while sleep 1; do
    find somedir | entr -d rsync -vr somedir/ remote.xyz:somedir/;
done
```

You could probably do something similar with [s3 sync].

[s3 sync]: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html

**Comment by eradman** [comment]
Definitely, using a rsync or rsync-like facility is the way to go!
