### ISSUE TITLE
Notification for successful save?

### ISSUE THREAD

**Issue by AndrejusAnto** [eradman/entr#44]
Maybe i am stupid and there is a way, it would nice to have some kind of notification, when save is made i.e. when doing some coding and getting errors in terminal, it is hard to tell that the code is correct when saving because you not always looking at terminal when saving and one have to cancel entr and run again to make sure there are no errors.

**Comment by eradman** [comment]
What kind of a notification did you have in mind? Brightly colored text? An e-mail? A sound? A popup?

**Comment by AndrejusAnto** [comment]
For me "Brightly colored text" is fine, but sound and popup also would be nice to have, for "email" i am not sure.

**Comment by eradman** [comment]
This problem isn't specific to `entr`, since you can write any mechanism that suites your purposes. This is a script which simply prints PASS/FAIL in green or red depending on an exit code

```sh
#!/bin/sh
if [ $1 == "0" ]; then
    printf "\e[32m"PASS"\e[0m\n"
else
    printf "\e[31m\e[7m"FAIL"\e[0m\n"
fi
exit $1
```

Then run using

```
ag -l | entr sh -c 'make; ./passfail $?'
```

(substitute `make` with your build command)

**Comment by AndrejusAnto** [comment]
Thanks, good enough, just needed to change == to =. Is it possible to implement same feature to entr?

**Comment by eradman** [comment]
I've having a difficult time envisioning what a generic implementation of this feature would mean. Here are some examples of a few other patterns you might use

```
ag -l | entr redgreen make
```

```
ag -l | entr sh -c 'make | highlight-warnings'
```

```
ag -l | entr sh -c 'make || tail build.log'
```

I'll leave this ticket open for a bit to see if anyone else chimes in with ideas.
