### ISSUE TITLE
Homebrew package recommended?

### ISSUE THREAD

**Issue by zachvalenta** [eradman/entr#45]
Seems to be available as a Homebrew package. 
```sh
$ brew search entr
==> Formulae
entr                     libtorrent-rakshasa      libtorrent-rasterbar     opentracing-cpp          pinentry ✔               pinentry-mac
```

[But `README.md` recommends using Make for install](https://github.com/eradman/entr#source-installation---bsd-mac-os-and-linux). Just curious if Homebrew is not recommended for any particular reason.

**Comment by eradman** [comment]
I used to list this in the README, but the list distributions and package managers grew large. Somewhere I saw a web site that would track the packaged version for each distribution and allowed you to embed this chart in the README. I'll see if I can find this site again.

Really I think this information would be useful on _every_ github project and doesn't belong in the README at all since the version packaged for each platform/distribution is constantly changing. It be cool if github let you enable this display for every project page.

**Comment by eradman** [comment]
This isn't the site I was thinking of, but close!

![homebrew](https://img.shields.io/homebrew/v/entr)
![homebrew](https://img.shields.io/fedora/v/entr)

where the markdown is

```
![homebrew](https://img.shields.io/homebrew/v/entr)
![homebrew](https://img.shields.io/fedora/v/entr)
```

**Comment by zachvalenta** [comment]
Yep, would be nice to avoid maintaining a mapping of versions to os package managers.

**Comment by zachvalenta** [comment]
> Somewhere I saw a web site that would track the packaged version for each distribution and allowed you to embed this chart in the README.

[Repology](https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager)?

**Comment by eradman** [comment]
@zachvalenta yes! That's what I was looking for

https://repology.org/badge/vertical-allrepos/entr.svg

There's still a problem: I this is a long list, and I don't really want to show this in-line. I wish there was a way to display this as part of the github sidebar

**Comment by zachvalenta** [comment]
I agree that's it's unwieldy for the README. Maybe just lob it into Github's wiki for the repo? That's what Zig seems to be doing [here](https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager).

**Comment by eradman** [comment]
I added the vertical badge bar to the home page: http://eradman.com/entrproject/

Thanks all for the input!

**Comment by eradman** [comment]
Sorry to backtrack here, but the repology.org badges aren't quire the right solution either:

1. They color out-of-date versions red, which is unfair to distributions that don't have a fast rolling release
2. When I cut a new release of entr I don't want everything labeled as out-of-date! The previous version will work fine for most people
3. "LTS" distributions always have laughably out-of-date packages; I don't want to see those
4. Many of these distributions are obscure; they clutter the list
