### ISSUE TITLE
Use entr to automate "source .bashrc"

### ISSUE THREAD

**Issue by lukosevicius** [eradman/entr#46]
I try to use:
`ls ~/.bashrc | entr -p source ~/.bashrc`
But I get an error:
`entr: exec source: No such file or directory`

What would be the correct way to automate sourcing .bashrc?

**Comment by eradman** [comment]
`source` or just `.` is a shell idiom, so you can only use it within a shell

```
ls ~/.bashrc | entr -p bash -c 'source ~/.bashrc; echo "done"'
```

This is the same as

```
ls ~/.bashrc | entr -p bash -l -c 'echo "done"'
```

 But only applies to the new shell which then exists. This will show errors in the `.bashrc` syntax, but won't be useful otherwise. What were you hoping to accomplish?

**Comment by lukosevicius** [comment]
Thanks for the reply!
I just wanted .bashrc to be automatically sourced after I do changes there. So I wouldn't have to do it myself every time.

**Comment by eradman** [comment]
Were you hoping to apply the new `.bashrc` across all shells, or just one? The environment is local to each shell, so there is no way to apply such a change globally

In tmux you could possibly automate this by running a command in separate window. This will send commands to pane no. 2

    tmux send-keys -t 2 "source ~/.bashrc" C-m

**Comment by eradman** [comment]
Hopefully the example with tmux provided you with some ideas, but there's really no good way to automate this.
