### ISSUE TITLE
clear option without blinking

### ISSUE THREAD

**Issue by ryuheechul** [eradman/entr#49]
_I'm not sure if it's even possible but I'm just thinking out-loud for now._

Would it be possible to for `entr` to redraw the result of command with out blinking when using option `-c`?

(_btw, _`entr`_ is pretty cool_ 👍)

**Comment by ryuheechul** [comment]
I actually just discovered a workaround so I'm sharing that here for anyone would like to know.

```
# before 
ls afile | entr -c ./transform.sh \_

# after
ls afile | entr ./transform.sh \_ > output

## in a saperate shell instance
less +F output

# ./transform.sh: a hypothetical script that transform the file format to another. you can replace with `cat` if you want
```

**Comment by eradman** [comment]
Clearing the screen just isn't going to be smooth.  `entr` literally calls `/usr/bin/clear`
Thanks for sharing that hack!
