### ISSUE TITLE
use aliases command in entr

### ISSUE THREAD

**Issue by nicola-lunghi** [eradman/entr#50]
Hi
I have an alias set like
alias my_cmd='./do_something && ./do_something_else && echo "done"'

how can I use it with entr like

git ls-files | entr my_cmd

??

**Comment by iamleot** [comment]
Hello @nicola-lunghi!
Probably the easiest way is just using a script instead of having an alias.

**Comment by nicola-lunghi** [comment]
Hi I just found that I can do

`git ls-files | entr sh -c "${BASH_ALIASES[my_cmd]}"`

In bash > 4.0

:-)

**Comment by eradman** [comment]
I agree with @iamleot that a script it usually the most strait-forward thing to do:

```
git ls-files | entr ./build.sh
```

This is worth it even for a one-line script because when you `cd` to the directory it's obvious what to do.  Thanks for posting your solution as well! Closing

**Comment by nielsbom** [comment]
I use quite a lot of aliases, having entr be able to use them directly would be very comfortable.

I don't know how to write C, but I'm interested to know how/why this was not implemented. Are  aliases special or difficult in some ways?

Could I write a PR to enable this functionality? Would you accept such a PR @eradman ?

**Comment by eradman** [comment]
Aliases are special because they're not part of the environment, they're a feature of the shell. This means `entr` can't inherit or inject them.

@nielsbom it's good that you brought this back up because there is a simple we can do, namely run shell with the login `-l` flag:

    ... | entr sh -l -c "..."

Each shell is different, but here is the relevant part from the bash(1) man page

> When bash is invoked as an interactive login shell, or as a non-interactive shell with the `--login` option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for `~/.bash_profile`, `~/.bash_login`, and `~/.profile`, in that order, and reads and executes commands from the first one that exists and is readable.

Another option is to source a file that defines aliases directly

    ... | entr sh -c ". ./profile; ..."

**Comment by eradman** [comment]
Closing since the use of shell aliases it outside the scope of what `entr` should or can take responsibility for.

As noted, files can be sourced manually

```
... | entr -s '. .myenv.sh; ...'
```
