### ISSUE TITLE
reload-browser can't reload when different workspace

### ISSUE THREAD

**Issue by zdmgmail** [eradman/entr#51]
I use i3wm, and http://eradman.com/entrproject/scripts/reload-browser

if browser not in current workspace, it will

```
echo "unable to signal an application named \"$app\"" 
```

is there any way to solve this?

**Comment by zdmgmail** [comment]
if use two monitor, only works when browser in these two monitor's current workspace

**Comment by eradman** [comment]
I tried to replicate this (I'm using using dwm) using two monitors as well as multiple workspaces, and wasn't able to replicate this. There are many nasty edge cases when using xdotool. Does removing `--onlyvisible` help?

**Comment by zdmgmail** [comment]
> I tried to replicate this (I'm using using dwm) using two monitors as well as multiple workspaces, and wasn't able to replicate this. There are many nasty edge cases when using xdotool. Does removing `--onlyvisible` help?

then output this:

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  422
  Current serial number in output stream:  423
unable to signal an application named "brave"

I tried this vim plug also have same problem, https://github.com/lordm/vim-browser-reload-linux, may be  i3wm problem?

**Comment by eradman** [comment]
This may indicate a problem with i3wm, but but just as likely this is a weirdness with X. Not sure where to go with this question. Perhaps xdotool-users@googlegroups.com? (see http://www.semicomplete.com/projects/xdotool/)
