### ISSUE TITLE
Ability to return utility exit code with oneshot option?

### ISSUE THREAD

**Issue by maiamcc** [eradman/entr#53]
I use `entr` in some extended functionality of the product I work on, and recently a user raised https://github.com/tilt-dev/tilt-extensions/issues/92 -- they're running into trouble b/c they're using `entr` as part of a Kubernetes job, and Kubernetes needs to know the exit code of the utility to declare that the job succeeded or failed.

Current behavior (from #29):
> The new -z option will return 0 if the utility was executed, or 1 if execution failed (permissions, non-existent path, etc.)

Any chance of the oneshot option returning the exit code of the utility (either by default, or when a specific flag is set)?

My first instinct would be to change [this line](https://github.com/eradman/entr/blob/2741bd17843dec22ebc1b32014784d5ef6150322/entr.c#L262) to `exit(WEXITSTATUS(status))` -- though there's no way to distinguish status code 1 meaning "entr failed to run your utility" and "utility ran and exited with status code 1".

[Just brainstorming, feel free to ignore] Assuming that's an important distinction to preserve, one solution might be to designate a specific exit code to mean "entr encountered an error" and assume that any other code is a return code from the utility. Though this framework only makes sense with the "one-shot" option, and it would be weird in other cases to have entr failures return status code 77 (or whatever). Maybe a specific flag (say, -Z) for "run entr as a one-shot and return back the status code of the utility (or 77 for entr failure)"?

**Comment by eradman** [comment]
I'll look at this in more carefully later, but yes I think returning the exit code of the utility when using `-z` makes sense. The one-shot option is relatively new, and changing it's behavior probably wouldn't affect anyone adversly.

**Comment by eradman** [comment]
@maiamcc your pull request was on the right track. I simplified it a bit further by getting rid of the use of a special exit code (99) in commit c564e6b. Sync with master and let me know if this behaves the way you would expect.

**Comment by maiamcc** [comment]
Yep, perfect! Added to https://github.com/tilt-dev/tilt-extensions/pull/93, thanks for your help.
