### ISSUE TITLE
Force kill process on file change?

### ISSUE THREAD

**Issue by Jonatino** [eradman/entr#54]
I'm using the following command
```ls *.zip | entr ./restart.sh```

Restart.sh
```
#/bin/bash
pkill -f "update-server"
rm -rf cache
rm -rf update-server
unzip ./update-server.zip
./update-server
```

This script kills a process, unzips a folder and restarts it. The problem is this process is a server which stays alive forever. Is there any option to make entr force kill this process when changes are detected? Thanks.

**Comment by Jonatino** [comment]
nvm `-r` works.

**Comment by eradman** [comment]
Cool! The `-r` option also creates a process group so that all child processes receive the termination signal as well.
