### ISSUE TITLE
Python Breakpoints

### ISSUE THREAD

**Issue by mogwai** [eradman/entr#58]
Thank you for creating this, it is an awesome very neat program.

I'd like to be able to use the program while debugging python code so that when a file changes, the process that is  running (PDB) exits and restarts the entire python program.

You mention this issue at the end of the documentation https://eradman.com/entrproject/ but I was wondering if there was a way of getting this to work? 

```
  File "/home/harry/miniconda3/envs/audiomentations/lib/python3.8/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
RuntimeError: input(): lost sys.stdin
```

**Comment by eradman** [comment]
Your question is about how to use restart option `-r` with a process that uses a TTY. Tell me know if this works for you:

One way is to fire up a tmux session and use `entr` to exit and restart the process:

    entr tmux send-keys -t .0 C-c ./cmd.py C-m

Where `.0` is the pane (can be more specific: session:window.pane)

**Comment by mogwai** [comment]
The debugger itself requires the quit command to be sent, and the \ seems to be required to add spaces in between the commands. 

This seems to work:
```
find . -name  "*.py" | entr tmux send-keys -t .0 quit C-m \ pytest\ --maxfail=1 C-m
```

I'll see if there is a way to extend this to create a pane automatically.

**Comment by eradman** [comment]
Now  the problem is that the solution is getting complex! Sometimes I write a script for starting a development environment, which takes a bit of time to set up the first time, but can be copied to other projects. Example:

```sh
#!/bin/sh

session=reload-pdb
tmux new-session -s "$session" -d

window=$session:0

tmux split-window -t $window -v -p 70
tmux send-keys -t $window "find . -name '*.py' | entr echo /_" C-m
tmux select-pane -t $window.0

tmux -2 attach-session -t "$session"
```
