### ISSUE TITLE
Entr: trying to trigger function while monitoring file change

### ISSUE THREAD

**Issue by atipico** [eradman/entr#6]
I'm trying to monitor some files with entr:

	do_it(){ echo Eita!; }
	while true; do ls folder/* more-folder/* | entr -pd do_it; done
	>> entr: exec do_it: No such file or directory

However, this works:

	while true; do ls folder1/* folder2/* | entr -pd echo Eita!; done

What am I doing wrong?

I am trying to use entr to help me with epub editing. So I this function will trigger an update command to a epub viwer as well as refresh a window in a web browser. (I'd love to see more real examples that would help me doing it...)

**Comment by eradman** [comment]
The problem there is that the function you defined is local to your current shell, so it cannot be run by external commands

```
$ do_it(){ echo Eita!; }
$ /usr/bin/time do_it
time: do_it: No such file or directory
        0.00 real         0.00 user         0.00 sys
$ /bin/sh -c 'do_it'
sh: do_it: not found
```

**Comment by atipico** [comment]
This code works, look:
	do_it & while inotifywait -e close_write folder1/* folder2/* -m; do do_it; done

Even if I write:
	export -f do_it

I got as a return: "entr: exec do_it: No such file or directory". I think it has something to be with the use of "exec" by entr... Does it make sense? The error "exec...: No such file or directory" is not exclusive of entr.

**Comment by eradman** [comment]
A function can be exported to a subshell, but you cannot execute a function with an external program. If you want to execute shell functions, you can write a loop such as this

```
#!/bin/sh

do_it(){ echo 'Eita!'; }

while true; do
    do_it
    ls folder1/* folder2/* | entr -pd -s 'kill $PPID'
done
```

**Comment by atipico** [comment]
Okay, I got it. Now, is there a way to run the function after entr is called? I tried:

`entr -pd -s 'kill $PPID' && do_it`

`entr -pd -s 'kill $PPID' & do_it`

`entr -pd -s 'kill $PPID' ; do_it`

but none of these worked...

**Comment by eradman** [comment]
`&` will background the process, and `&&` will run only on exit code `0` so that's not what you want. The last option you listed should work

```
entr -pd -s 'kill $PPID' ; do_it
```
is equivalent to 
```
entr -pd -s 'kill $PPID'
do_it
```
Running the shell with `set -x` might help debug this

**Comment by atipico** [comment]
Thank you very much. 

It enters a loop:

`entr -pd -s 'kill $PPID' ; do_it`
`entr: cannot create kqueue: Too many open files`

**Comment by eradman** [comment]
How many files are under the directories you're piping into `entr`? Also what is the open file limit (`ulimit -n`)?

here are the instructions for raising the max number of open files:

http://eradman.com/entrproject/limits.html

**Comment by atipico** [comment]
> How many files are under the directories you're piping into entr?
Files for an normal EPUB file. No more than 100.

> ulimit -n
1024

If you need any more information, please, just tell.

**Comment by eradman** [comment]
Super! Glad it's working for you.

**Comment by OliverBrotchie** [comment]
> A function can be exported to a subshell, but you cannot execute a function with an external program. If you want to execute shell functions, you can write a loop such as this
> 
> ```
> #!/bin/sh
> 
> do_it(){ echo 'Eita!'; }
> 
> while true; do
>     do_it
>     ls folder1/* folder2/* | entr -pd -s 'kill $PPID'
> done
> ```
> 
> (`entr` doesn't have a "one-shot" option, so `kill $PPID` is used to terminate itself when a file changes)

This code won't exit with ctrl+c, is there a workaround to this??

**Comment by eradman** [comment]
@OliverBrotchie, since 4.5 entr does have a one-shot option: `-z`.

I bet `ctrl-c` doesn't work because the shell loop doesn't give you time to interrupt it. Try replacing `true` with `sleep`

```sh
#!/bin/sh

do_it(){ echo 'Eita!'; }

while sleep 0.1; do
    do_it
    ls folder1/* folder2/* | entr -pdz echo "reloading"
done
```

**Comment by sgon00** [comment]
I am having a similar question, but I don't really like the solution provided in this thread so far, maybe it's because I am running multiple entr processes without while loop.
Then I figured out another solution by creating a second shell script and source it. Hope it can help others.

file `utils.sh`:

```sh
do_it() { echo it; }
do_that() { echo that; }
```

file `run.sh`:

```sh
ls folder1/* | entr sh -c 'source utils.sh; do_it' &
ls folder2/* | entr sh -c 'source utils.sh; do_that'
```
