### ISSUE TITLE
Doc suggestion: comparison w/ similar tools

### ISSUE THREAD

**Issue by p3r7** [eradman/entr#62]
Hi.

I just stumbled upon your project which seems nicely put.

I have a very simple suggestion.

I guess quite a few people are more familiar w/ the venerable [incrond(8)](https://linux.die.net/man/8/incrond) (Linux) and [filewatcherd(8)](https://www.freebsd.org/cgi/man.cgi?query=filewatcherd&apropos=0&sektion=8&manpath=FreeBSD+11-current&format=html) (FreeBSD) for this kind of functionality.

A quick section for X-linking similar projects w/ a brief rundown of differences could be beneficial in choosing the right tool for the right job.

As I understand it:
- `entr` is more for on-demand command launch, taking list of files to watch as a piped input while others rely on their own crontab-like configuration
- by this on-demand approach, `entr` is more suitable for interactive development (e.g. CI test) while others are more for backend automation applications (e.g. provisioning)
- `entr` is more cross-platform (even though `incrond` appears to have been ported to BSD)

But this interpretation might be wrong, hence the benefit of having a more explicit comparison.

**Comment by eradman** [comment]
At one point I did keep keep track of similar/related projects which was accessible on http://entrproject.org/. Eventually the list became unwieldy, and hard to summarize in a meaningful way. (I also lost track myself).

This really is a more general problem of navigating software--my sense is that blog posts still serve as a guide for many. A wiki would also be a solution, but they tend to fall out of date.
