### ISSUE TITLE
rpi arch64 segmentation fault

### ISSUE THREAD

**Issue by Makurisan** [eradman/entr#66]
Would be nice it would running on rpi4 64bit.
Tried:

 find v-hub.ko | entr sh -c 'clear'
[1]    15504 done                find v-hub.ko |
  15505 segmentation fault  entr sh -c 'clear'

checked on:

Linux pi 5.10.4-v8+ #1389 SMP PREEMPT Wed Jan 6 13:52:18 GMT 2021 aarch64 GNU/Linux

**Comment by eradman** [comment]
What version of `entr` do you have installed?  Does the same thing happen if you build from source?

**Comment by Makurisan** [comment]
I downloaded the latest version and build it from scratch.  One version for pi3 and one pi4. I have no problem with Pi3. Here it is a 32bit system.

**Comment by eradman** [comment]
Thanks for confirming @Makurisan. I'm going to get my hands on an arch64 system to debug this on. If you could, send me the following output from `gdb`

```sh
ulimit -c                   # Allow core dumps
make clean                  # Build with debuggin
CFLAGS=-g make
ls * | ./entr echo /_       # Do something to trigger a segfault
gdb -q ./entr -c entr.core  # print backtrace
```

**Comment by Makurisan** [comment]
ubuwin@pi:~/entr(master○) » ulimit -c                   # Allow core dumps
0
ubuwin@pi:~/entr(master○) » make clean                  # Build with debug symbols
rm -f entr entr_spec *.o
ubuwin@pi:~/entr(master○) » CFLAGS=-g make
cc -g -D_GNU_SOURCE -D_LINUX_PORT -Imissing -DRELEASE=\"4.8\" missing/strlcpy.c missing/kqueue_inotify.c entr.c -o entr
ubuwin@pi:~/entr(master○) » ls * | ./entr echo /_       # Do something to trigger a segf
ault
[5]    4421 done                ls --color=tty * |
       4422 segmentation fault  ./entr echo /_
ubuwin@pi:~/entr(master○) » gdb -q ./entr -c entr.core  # print backtrace         139 ↵
Reading symbols from ./entr...done.
/home/ubuwin/entr/entr.core: No such file or directory.
(gdb)

**Comment by eradman** [comment]
Edit: that should have been
```
ulimit -c unlimited
```

On Ubuntu this shows up as `core`, not `entr.core`

**Comment by Makurisan** [comment]
Core was generated by `./entr echo /_'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  process_input (file=0x7fa51f0880 <_IO_2_1_stdin_>, files=0x0, max_files=1732920072)
    at entr.c:310
310                             files[n_files] = malloc(sizeof(WatchFile));
(gdb)

**Comment by eradman** [comment]
That is strange, 1732920072 is not only an unreasonable value but should impossible since this line guards against values greater than 2^19

```
176:  open_max = min(524288, open_max);
```

What is the output of this program?

```c
/* print_limits.c */
#include <stdio.h>
#include <unistd.h>
#include <sys/resource.h>

int main() {
        struct rlimit rl;
        getrlimit(RLIMIT_NOFILE, &rl);

        printf("rlim_cur: %lu\n", (unsigned long)rl.rlim_cur);
        printf("rlim_max: %lu\n", (unsigned long)rl.rlim_max);
        printf("_SC_OPEN_MAX: %lu\n", (unsigned long)sysconf(_SC_OPEN_MAX));
}
```

Build using

```
cc print_limits.c
./a.out
```

**Comment by Makurisan** [comment]
rlim_cur: 1024
rlim_max: 1048576
_SC_OPEN_MAX: 1024

**Comment by eradman** [comment]
Thanks @Makurisan, the values of `rlim_cur`, `rlim_max`, `_SC_OPEN_MAX` look fine. I'm going to try to reproduce this as soon as I have an aarch64 system to test on.

**Comment by stevenhollett** [comment]
Crashes on x86_64 as well.  

The variable open_max wasn't initialized in all cases.  I've created pull request #68 to address this issue.

**Comment by eradman** [comment]
Thanks @stevenhollett
So this wasn't even architecture dependent, it could happen on any Linux system

**Comment by Makurisan** [comment]
The pull request #68 solves the problem.
