### ISSUE TITLE
core dumped at X startup on OpenBSD -current

### ISSUE THREAD

**Issue by daeluk** [eradman/entr#72]
I'm getting core dumps on OpenBSD -current having this line in $HOME/.xsession (runs at X startup):

```
readlink -f $HOME/.Xresources | entr -p xrdb -merge /_ &
```

This happens both with the 4.8 version from ports as well as HEAD compiled from scatch.

Running the same command manually in the foreground works as intended.
Running the same command manually in the background doesn't abort but doesn't doesn't seem to work, i.e.
it doesn't seem to run the supplied command.

Here's the output from some relevant commands:

```
$ uname -a
OpenBSD 6.9 GENERIC.MP#457 amd64
```

```
$ gdb src/clones/entr/entr ./entr.core # compiled with CFLAGS=-g make
GNU gdb 6.3
Core was generated by `entr'.
Program terminated with signal 6, Aborted.
Loaded symbols for /home/tcht/src/clones/entr/entr
Reading symbols from /usr/lib/libc.so.96.0...done.
Loaded symbols for /usr/lib/libc.so.96.0
(gdb) bt
#0  ioctl () at /tmp/-:3
#1  0x00000379167dd73d in _libc_tcsetattr (fd=Variable "fd" is not available.
) from /usr/lib/libc.so.96.0
#2  0x00000376debee5a6 in main (argc=Variable "argc" is not available.
) at entr.c:602
Current language:  auto; currently asm
(gdb) list
602			xtcsetattr(0, TCSADRAIN, &character_tty);
603		if ((reopen_only == 1) || (collate_only == 1)) {
604			nev = xkevent(kq, NULL, 0, evList, 32, &evTimeout);
605		}
606		else {
607			nev = xkevent(kq, NULL, 0, evList, 32, NULL);
608			dir_modified = 0;
609		}
610	
611		if ((nev == -1) && (errno != EINTR))
```

```
$ readlink -f $HOME/.Xresources | entr -p echo /_ # triggering
/home/tcht/.Xresources # works
```

```
$ readlink -f .Xresources | entr -p echo /_ & # doesn't seem to do anything when triggered
[1] 51513 4068
$ 
[1] + Done                 readlink -f .Xresources |
      Stopped (tty output) entr -p echo /_ 
```

I'm at the end of my debugging abilities here, unfortunately.
If you need anything else please let me know :)

**Comment by eradman** [comment]
Thanks for the detailed report. Does adding the `-n` flag change or solve this problem?

**Comment by daeluk** [comment]
It absolutely did, thank you :)
I guess I didn't read the manual carefully enough.

**Comment by eradman** [comment]
@daeluk I took a closer look at this; getting SIGABRT is definitely not expected! It turns out this is a real bug. 
Commit fb490f2 adds error handling for the condition where `tcgetattr(3)` fails:

    entr: unable to get terminal attributes, use '-n' to run non-interactively
