### ISSUE TITLE
Why is it called entr?

### ISSUE THREAD

**Issue by nedbat** [eradman/entr#80]
entr is very handy, but I use it infrequently, and then can't remember what it is called, because there's no mnemonic value to "entr".  Is there a reason for the name? Maybe that would help me! :)  Thanks <3

**Comment by eradman** [comment]
Hi @nedbat, the title in the README has the answer: 

Event Notify Test Runner

It's also a play on the pronunciation of the "Enter" key

**Comment by nedbat** [comment]
Thanks, I missed that somehow. I was looking in the man page :)
