### ISSUE TITLE
`entr` to test a game

### ISSUE THREAD

**Issue by ffaf1** [eradman/entr#85]
I am developing a small terminal game and decided to use `entr` to test it. I invoke it like this:

    find src/ -name '*.hs' | entr cabal run invalicabile-nebbia

But when I save a file the game does not get reloaded (I have to quit the game first). `-r` option seemed alluring, but that blocks input if I understood it correctly. What can I do to make entr work in my case? I can provide repo and compilation instructions if needed.

**Comment by eradman** [comment]
What is the process state when you run this command? (`ps -x | grep cabal`)

**Comment by ffaf1** [comment]
```
***@***.***:~/spool/advgame/invalicabile-nebbia$ ps -x | grep cabal
3206689 pts/5    S+     0:00 entr cabal run invalicabile-nebbia
3211666 pts/5    Sl+    0:00 cabal run invalicabile-nebbia
3216850 pts/7    S+     0:00 grep cabal
```

Il 23 novembre 2021 alle 06:32 Eric Radman ha scritto:

**Comment by eradman** [comment]
Okay, it appears that `cabal run` is sleeping and not exiting. `-r` is useful if you're running a process that does not exit on it's own--such as a web server.

Does your program require access to `STDIN`? If so `-r` won't work

```
     -r      Reload a persistent child process.  As with the standard mode of
             operation, a utility which terminates is not executed again until
             a file system or keyboard event is processed.  SIGTERM is used to
             terminate the utility before it is restarted.  A process group is
             created to prevent shell scripts from masking signals.  entr
             waits for the utility to exit to ensure that resources such as
             sockets have been closed.  Control of the TTY is not transferred
             to the child process.
```

**Comment by ffaf1** [comment]
> Does your program require access to `STDIN`? If so `-r` won't work

Alas it does, since it is a game.

Il 23 novembre 2021 alle 07:22 Eric Radman ha scritto:

**Comment by eradman** [comment]
There is a way to solve this with `tmux`, namely, start two panes and then use `entr` to send keys to the other pane when files change

    find src/ -name '*.hs' | entr tmux send-keys -t .0 C-c 'cabal run invalicabile-nebbia' C-m

This will send Control+C to exit the process in pane `.0` followed by the command to restart it. This is a very flexible pattern can be used to turn the crank on any kind of command-line interface.

**Comment by ffaf1** [comment]
Excellent idea, I will put that into use!

Il 23 novembre 2021 alle 09:33 Eric Radman ha scritto:

**Comment by ffaf1** [comment]
Works like a charm, this can be closed!

Il 23 novembre 2021 alle 09:33 Eric Radman ha scritto:

**Comment by eradman** [comment]
Super!  Closing.
