### ISSUE TITLE
NEWS requires an update

### ISSUE THREAD

**Issue by wavexx** [eradman/entr#86]
Given that 5.1 is tagged, the first entry in NEWS is probably outdated:

https://github.com/eradman/entr/blob/b6eab73599d5b40230f36d18aef9be3a1a051cf2/NEWS#L1

**Comment by eradman** [comment]
Are you sure? If you look at the 5.1 tag (or master) it has been updated

https://github.com/eradman/entr/blob/5.1/NEWS

**Comment by wavexx** [comment]
Huh, you're right of course. I'm not sure why I was stuck on the old revision when clicking on it through github, but even the linked blob refers to the old version so somehow I didn't imagined it.

Anyway, closing!

**Comment by eradman** [comment]
Glad to hear it's all good!

As always, thanks for maintaining the Debian package--I hear from people, and rely on it!
