### ISSUE TITLE
-z to preserve exit code doesn't work

### ISSUE THREAD

**Issue by huglovefan** [eradman/entr#90]
noticed when testing the patch for https://github.com/eradman/entr/issues/89

```
$ ls -d /bin/sh | entr -zs 'echo hi; exit 4'
hi
bash returned exit code 0
$ echo $?
0
```

the test script doesn't exercise this properly, it uses `||` which causes it to skip the assert if the wait returns 0

it fails if i change it to a `;`:

```patch
diff --git a/system_test.sh b/system_test.sh
index 76a2d5d..003c2ef 100755
--- a/system_test.sh
+++ b/system_test.sh
@@ -112,7 +112,7 @@ try "exec a command using one-shot option exit code from child"
 	setup
 	ls $tmp/file* | ./entr -z sh -c 'exit 4' &
 	bgpid=$! ; zz
-	wait $bgpid || assert "$?" "4"
+	wait $bgpid ; assert "$?" "4"
 
 try "restart a server when a file is modified using one-shot option"
 	setup
```

there are 31 instances of ` || assert` in the file, i think they should all be ` ; assert`

i tested this on linux if that matters (using entr compiled from git)

**Comment by eradman** [comment]
Commit 10657ab avoids skipping assertions when `wait` exits 0. @huglovefan thanks for pointing out this mistake!
