### ISSUE TITLE
advantages over inotify?

### ISSUE THREAD

**Issue by ahillio** [eradman/entr#95]
Hello! The README.md says `entr` uses `inotify` but it doesn't compare the two programs at all. Does `entr` do anything that `inotify` doesn't do or does it make things easy which `inotify` on its own makes difficult? Or is advantage of `entr` that it also works on BSD systems without inotify and so using `entr` is more cross-platform?

**Comment by arkamar** [comment]
The `README.md` mentions [`inotify(7)`](https://man7.org/linux/man-pages/man7/inotify.7.html) API which is a Linux specific alternative to [`kqueue(2)`](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2) from BSD world; kind of, it is slightly more complicated :) One must dig deeper to man pages to understand the difference.

I am not sure what `inotify` program are you talking about.

**Comment by ahillio** [comment]
Oh whoops... I confused the `inotify` packages...

Are you familiar with `inotifywait` provided by the `inotify-tools` package?

`inotifywait` also runs arbitrary commands when files change.

**Comment by arkamar** [comment]
Yes, I know `inotifywait`, but I never used it to a degree to call myself familiar with it. Anyway, looking to a man page, `inotifywait` just waits for any or specified event(s) on file(s) and exits on that event. This program seems to be most useful in shell scripts and it would be possible to craft a script with similar functionality to `entr` with this command.

On the other hand, `entr` waits for events on file(s) and runs specified command every time any event of any file appears. `entr` is much more user utility that can be used just on its own, without any further scripting. But you can use it in scripts as well, of course.

Both commands overlap in some aspects. `entr` is much more simple to use in my opinion. It is possible to fine tune events with `inotifywait` but some other shell scripting would be still required. The choice depends on what you want to accomplish :)

And one last note, `entr` is crossplatform but `inotifywait` is Linux specific.

### Examples:

Two examples below do similar job, watch for changes in `test` file and prints `ls -lha test` on an event.

inotifywait:

```sh
while true
do
	inotifywait test >/dev/null 2>&1
	ls -lha test
done
```

entr:

```sh
ls test | entr ls -lha test
```

**Comment by ahillio** [comment]
Awesome. Thanks for clarifying :)

**Comment by tartley** [comment]
'inotify-wait' takes a `--monitor` flag, which modifies the behavior so that it does not exit on the first event. Since it outputs a line of info for each received event, this means that the canonical usage of inotify-wait is usually something like:

```
inotifywait --monitor --event=close_write,moved_to README | while read; do
   date
done
```

Where the `date` command will be run whenever the README file is written to or overwritten by a move.
