### ISSUE TITLE
Using redirection with entr

### ISSUE THREAD

**Issue by malcolmsailor** [eradman/entr#99]
The `>` operator isn't working with entr in the way I expect it to. E.g., if I run

```
ls foo | entr -p echo doo > bar
```

Each time I modify `foo`, 'doo' is *appended* to `bar`, rather than overwriting its contents (i.e., what I expect `>>` to do). I suspect this has something to do with some subtle shell behavior that eludes me. Is there a way to get the same result as the usual `>` redirection?

Thanks for a great tool!

**Comment by eradman** [comment]
Glad entr has been useful to you!

If you want pipes and other redirection to act as a single command, start a shell:

```
ls foo | entr -p sh -c 'doo > bar'
```

or

```
ls foo | entr -p -s 'doo > bar'
```

**Comment by malcolmsailor** [comment]
Fantastic, thanks!
